---
- name: Inventory from tag
  when: dnac_tag_to_update | default('')
  block:
    - name: Get tags details
      cisco.dnac.tag_info:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify | default(omit) }}"
        name: "{{ dnac_tag_to_update }}"
      register: tag_details

    - name: Get hosts for the specified tag
      when: tag_details.dnac_response.response
      cisco.dnac.tag_member_info:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify | default(omit) }}"
        id: "{{ tag_details.dnac_response.response[0].id }}"
        memberType: networkdevice
        offset: "{{ item }}"
      loop: "{{ range(1, 10000, 500) | list }}"
      loop_control:
        break_when: dnac_devices_to_update_from_tag.dnac_response.response | default([]) | length < 500
      register: dnac_devices_to_update_from_tag

- name: Inventory from hostlist
  when: dnac_hosts_to_update_url | default([])
  block:
    - name: Download file with the list of hosts
      ansible.builtin.get_url:
        url: "{{ dnac_hosts_to_update_url }}"
        dest: /tmp/hostlist.txt
        mode: '0644'
      check_mode: false

    - name: Read hostlist file
      ansible.builtin.slurp:
        src: /tmp/hostlist.txt
      register: dnac_hosts_to_update

    - name: Get devices by hostname
      cisco.dnac.network_device_info:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify | default(omit) }}"
        hostname: "{{ (dnac_hosts_to_update.content | default([]) | b64decode).splitlines() }}"
      register: dnac_devices_to_update_from_hostlist

- name: Build complete inventory
  ansible.builtin.set_fact:
    dnac_devices_to_update: "{{ ((dnac_devices_to_update_from_tag.results | default([]) | map(attribute='dnac_response.response'))[0] | default([]) +
                                 dnac_devices_to_update_from_hostlist.dnac_response.response | default([])) |
                                unique(attribute='hostname') }}"
