---
- name: Refresh details on devices from current batch
  cisco.dnac.network_device_info:
    dnac_host: "{{ dnac_host }}"
    dnac_username: "{{ dnac_username }}"
    dnac_password: "{{ dnac_password }}"
    dnac_verify: "{{ dnac_verify | default(omit) }}"
    hostname: "{{ device_list | map(attribute='hostname') }}"
  register: dnac_devices_current_batch

- name: Fail if not Reachable devices exceed threshold
  ansible.builtin.fail:
    msg: "Non Reachable devices in the current batch exceed the threshold."
  when: dnac_devices_current_batch | rejectattr('reachabilityStatus', 'equalto', 'Reachable') | length > dnac_batch_fail_threshold

# Add tasks that overwrite golden image

- name: Initiate device sync
  cisco.dnac.network_device_sync:
    dnac_host: "{{ dnac_host }}"
    dnac_username: "{{ dnac_username }}"
    dnac_password: "{{ dnac_password }}"
    dnac_verify: "{{ dnac_verify | default(omit) }}"
    payload: "{{ device_list | map(attribute='id') }}"
  register: image_sync_result

- debug:
    var: image_sync_result

- name: Wait for image distribution to complete
  cisco.dnac.network_device_image_info:
    dnac_host: "{{ dnac_host }}"
    dnac_username: "{{ dnac_username }}"
    dnac_password: "{{ dnac_password }}"
    dnac_verify: "{{ dnac_verify | default(omit) }}"
    networkDeviceUpdateStatus: DISTRIBUTION_IN_PROGRESS
  register: image_distribution_status
  until: not image_distribution_status.dnac_response
  delay: "{{ dnac_distribution_check_delay | default(15) }}"

- debug:
    var: image_distribution_status

# Add tasks to update reports
